### ISSUE TITLE
Récupérer un cinéma à partir de la localisation

### ISSUE THREAD

**Issue by antoine6348** [thomasMagalhaes30/AluilCine#11]
Récupérer les cinémas à partir de la longitude et de la latitude

**Comment by Amiralgaby** [comment]
get all avec condition

`/location/la=874.303&lon=33.29`

**Comment by Amiralgaby** [comment]
les 5 plus proches

**Comment by Amiralgaby** [comment]
Finalement avec `/location?latitude=34.483&longitude=5.4333&limit=5`

Le paramètre optionnel **limit** est là pour obtenir une quantité de cinema, dans l'exemple on en garde 5
