### ISSUE TITLE
CRUD catégorie (pas vraiment un crud)

### ISSUE THREAD

**Issue by thomasMagalhaes30** [thomasMagalhaes30/AluilCine#19]
Attention crud d'un enum

**Comment by Amiralgaby** [comment]
il nous faut une classe categorie ?

Parce que sinon comment on chope toutes les catégories ?

**Comment by thomasMagalhaes30** [comment]
Bonjour **Amiral**gaby ! 

Les categories seront un enum et pas une table en base donc pas besoin de categorie.
