### ISSUE TITLE
Avoir toutes les genres

### ISSUE THREAD

**Issue by thomasMagalhaes30** [thomasMagalhaes30/AluilCine#5]
Permet d'avoir tous les genres disponibles

**Comment by Amiralgaby** [comment]
on peut renommer en catégorie ? ou alors c'est catégorie qui devient genre ?

On parle de la même chose mais bon, on choisi un mot et c'est mieux ^^ ;)

**Comment by thomasMagalhaes30** [comment]
Genre = Gatégorie
